added custom brush such as blur and emboss
PicnicSupermarket/FingerPaintView pull request #2
Opened 2018-08-03 19:50 UTC by blkrt

Users can change brush type via radio type in bottom of screen

2018-08-08 18:10 UTC, FlorBosch requested changes
Thank you so much for your contribution 🎉 ! There are some minor comments that should be addressed before we can merge it.

2018-08-08 18:10 UTC, FlorBosch commented on .idea/vcs.xml
> +<?xml version="1.0" encoding="UTF-8"?>
This kind of file belongs to the IDE configuration and it should not be added into the repository.

2018-08-08 18:10 UTC, FlorBosch commented on app/src/main/java/tech/picnic/fingerpaintview/sample/SampleActivity.kt
> +
Remove empty line :)

2018-08-08 18:10 UTC, FlorBosch commented on app/src/main/res/layout/activity_sample.xml
> +        android:layout_width="200dp"
Is there any particular reason why these properties were changed?

2018-08-08 18:10 UTC, FlorBosch commented on fingerpaintview/src/main/java/tech/picnic/fingerpaintview/FingerPaintImageView.kt
> +    private val mEmboss = EmbossMaskFilter(floatArrayOf(1F,1F,1F) , 0.4F, 6F, 3.5F)
We don't follow this particular naming convention for field names. The `m` should be removed.

2018-08-08 18:10 UTC, FlorBosch commented on fingerpaintview/src/main/java/tech/picnic/fingerpaintview/FingerPaintImageView.kt
> +    private val mEmboss = EmbossMaskFilter(floatArrayOf(1F,1F,1F) , 0.4F, 6F, 3.5F)
There should be a whitespace after each `,` in the params (default Android Studio formatting should do the trick) :)

2018-08-08 18:10 UTC, FlorBosch commented on fingerpaintview/src/main/java/tech/picnic/fingerpaintview/FingerPaintImageView.kt
> +    var isBlur = false
`isBlur`, `countDrawn` and `isEmboos ` should be defined as `private` fields.

2018-08-08 18:10 UTC, FlorBosch commented on fingerpaintview/src/main/java/tech/picnic/fingerpaintview/FingerPaintImageView.kt
> +
Remove empty line :)

2018-08-08 18:10 UTC, FlorBosch commented on fingerpaintview/src/main/java/tech/picnic/fingerpaintview/FingerPaintImageView.kt
> +        isEmboos = false
These set of booleans (`isBlur`, `normal` and `isEmboos`) are representing the drawing mode which could be modeled as an enum. That would make the code much more simpler and maintainable if we want to add even more modes :)

2018-08-08 18:10 UTC, FlorBosch commented on fingerpaintview/src/main/java/tech/picnic/fingerpaintview/FingerPaintImageView.kt
> +        mBitmap = Bitmap.createBitmap(widthBitmap,
Compiler is throwing the following warning: `Avoid object allocations during draw/layout operations...`. This warning could be solved by creating the `bitmap` and `canvas` before calling `onDraw(...)`.

2018-08-08 18:10 UTC, FlorBosch commented on fingerpaintview/src/main/java/tech/picnic/fingerpaintview/FingerPaintImageView.kt
> +                if (isEmboos) paths[index].second.maskFilter = mEmboss
`paths[index].second` is used on multiple places. It can be extracted into a separate variable for simplicity.

2018-08-08 20:32 UTC, blkrt commented on app/src/main/res/layout/activity_sample.xml
> +        android:layout_width="200dp"
I had to change it because it wasn't fit with emulator's screen and after I forgot to return it

2018-08-08 21:29 UTC, blkrt commented
Requested changes applied, thank you for checking it.

2018-08-09 20:23 UTC, FlorBosch requested changes
Final round! 🎉

2018-08-09 20:23 UTC, FlorBosch commented on .idea/vcs.xml
> +<project version="4">
Sorry for the misunderstanding but the whole file shouldn't be commited.

2018-08-09 20:23 UTC, FlorBosch commented on fingerpaintview/src/main/java/tech/picnic/fingerpaintview/FingerPaintImageView.kt
> +        BLUR, EMBOSS, NORMAL
If the enum shouldn't be accessed from outside then it's better to make it private.

2018-08-09 20:23 UTC, FlorBosch commented on fingerpaintview/src/main/java/tech/picnic/fingerpaintview/FingerPaintImageView.kt
> +    private val defaultBlur = BlurMaskFilter(5F, BlurMaskFilter.Blur.NORMAL)
A nice idea could be to define `defaultEmboss` and `defaultBlur` as lazy. This way if none of the brush types are used then these fields are not initialized.
```
    private val defaultEmboss: EmbossMaskFilter by lazy {
        EmbossMaskFilter(floatArrayOf(1F, 1F, 1F), 0.4F, 6F, 3.5F)
    }
    private val defaultBlur: BlurMaskFilter by lazy {
        BlurMaskFilter(5F, BlurMaskFilter.Blur.NORMAL)
    }
```

2018-08-09 20:23 UTC, FlorBosch commented on fingerpaintview/src/main/java/tech/picnic/fingerpaintview/FingerPaintImageView.kt
> +        brushBitmap = Bitmap.createBitmap(widthBitmap,
Now that `brushBitmap` and `brushCanvas` are assigned in `onSizeChanged(...)` (really nice!! 🤓 ), there is no need for **widthBitmap** and **heightBitmap**. These fields should be removed.
```
brushBitmap = Bitmap.createBitmap(w, h, Bitmap.Config.ARGB_8888)
```

2018-08-09 20:23 UTC, FlorBosch commented on fingerpaintview/src/main/java/tech/picnic/fingerpaintview/FingerPaintImageView.kt
> +                else if (currentBrush == BrushType.BLUR) paintMaskFilter.maskFilter = defaultBlur
This block of code could be replaced with **when** so that we can make sure that all cases are covered. Something like:
```
            val path = paths[index]
            if (index >= countDrawn) {
                path.second.maskFilter =
                        when (currentBrush) {
                            BrushType.EMBOSS -> defaultEmboss
                            BrushType.BLUR -> defaultBlur
                            BrushType.NORMAL -> null
                        }
            }
            brushCanvas?.drawPath(path.first, path.second)
```

2018-08-09 20:23 UTC, FlorBosch commented on fingerpaintview/src/main/java/tech/picnic/fingerpaintview/FingerPaintImageView.kt
> +     */
Now when calling  emboss() or blur() the corresponding mode is enabled but it can't be disabled by calling these method, so the documentation of these methods should be updated.

2018-08-10 18:24 UTC, blkrt commented on .idea/vcs.xml
> +<project version="4">
Excuse me for my mistake, I got it.

2018-08-10 18:40 UTC, blkrt commented
I've fixed them, thank you so much for checking it.

2018-08-13 08:30 UTC, Stephan202 approved these changes
We should probably install a formatter, but let's consider that out of scope :)

2018-08-13 08:30 UTC, Stephan202 commented on fingerpaintview/src/main/java/tech/picnic/fingerpaintview/FingerPaintImageView.kt
> +            brushCanvas?.drawPath(paths[index].first, paths[index].second)
Here `paths[index]` is `path`.

2018-08-13 18:22 UTC, FlorBosch approved these changes

2018-08-13 19:53 UTC, merged